### ISSUE TITLE
Socket Timeout

### ISSUE THREAD

**Issue by FatuityCookie** [ilyabreev/ClickHouse.Net#11]
clickhouse-server-20.12.5.14-2  

Unhandled exception. System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没 有正确答复或连接的主机没有反应，连接尝试失败。.
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at ClickHouse.Ado.Impl.UnclosableStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadBytes(Int32 i)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadByte()
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadUInt()
   at ClickHouse.Ado.Impl.ProtocolFormatter.Handshake(ClickHouseConnectionSettings connectionSettings)
   at ClickHouse.Ado.ClickHouseConnection.Open()
   at ClickHouse.Net.ClickHouseDatabase.Open()

![image](https://user-images.githubusercontent.com/46119806/105004229-9d7c3f00-5a6e-11eb-8260-e3aff05e2d0a.png)
use  DBeaver 7.3.3 can use it!!!

**Comment by FatuityCookie** [comment]
port error use 8123 ,use 9000 is ok
